#include <stdio.h>
int main()
{
    char name = 'a';
    char symball = 'H';
    char _bitname = 'b';
    char name1 = 'k';
    char first1 = 'd';
    char  senss = 'l';
    char demo ='a';
    char test = 'o';
    char num = '2';
    char loops = 'F';
    char namee1 = 'a';
    char symball2 = 'o';
    char _bitname10 = 'n';
    char name1_ = 'w';
    char fir_st1 = 'q';
    char __senss = 'a';
    char d_emo ='z';
    char test21 = 'x';
    char num_1 = '4';
    char loops14 = 'q';
    char byte = 'D';
    char _count = 'c';
    char sign = 'g'; //23 
    char bt = 'P';
    char mingW = 'C';
    char _code = 'V';
    char First_letter = 'h';
    char located = 'S';
    char _bitname110 = 'c';
    char name8_ = 'v';
    char fir_st10 = 'b';
    char __senss01 = 'N';
    char d_emo23 ='l';
    char test8 = 'o';
    char num_9 = '8';
    char loops00 = 'i';  //36
    char capital_name = 'T';
    char second = 'B';
    char Lol = 'F';
    char side = 'c';
    char build = 'b';
    char harshil__0 = '3';
    char string = 'S';
    char gigabytes = 'g';
    char meto = 'F';
    char _developername = 'D';
    char firstletter__ = 'h';
    char meta =  'E';
    char delta21 = 'D';
}